layout: stacked
style: dark

url: https://MichaelCurrin.github.io
repository: MichaelCurrin/MichaelCurrin.github.io

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

google_analytics: UA-87705880-9

exclude:
  - "Makefile"
  - "LICENSE"
  - "LICENSE-source"
  - "README.md"
  - "vendor"
  - "Gemfile"
  - "Gemfile.lock"
# The last few only need to be excluded in Jekyll 3.

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
# behance: your_username
# dribbble: your_username
# facebook: your_username
# hackerrank: your_username
# instagram: your_username
# keybase: your_username
# linkedin: your_username
# mastodon: your_username
# medium: your_username
# stackoverflow: your_user_id
# telegram: your_username
# twitter: your_username
# unsplash: your_username
# vk: your_username
# website: http://your_website_url
# youtube: your_username

topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: Bash
    web_url: https://github.com/topics/bash
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/bash/bash.png

  - name: Web design

  - name: Jekyll
    web_url: https://github.com/topics/jekyll
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/jekyll/jekyll.png
