### Site metadata

repository: MichaelCurrin/MichaelCurrin.github.io

### Build settings ###

url: https://MichaelCurrin.github.io
baseurl: ""

permalink: pretty

google_analytics: UA-87705880-9

plugins:
  - jekyll-octicons

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - "LICENSE"
  - "LICENSE-source"
  - "README.md"
  - "Makefile"
  # Exclude in Jekyll 3 only
  - "vendor"
  - "Gemfile"
  - "Gemfile.lock"

### Theme settings ###

layout: stacked
style: dark

projects:
  # pushed OR stars
  sort_by: stars
  limit: 12
  exclude:
    archived: true
    forks: false
    projects:
    # - repo-name

# social_media:
# behance: your_username
# dribbble: your_username
# facebook: your_username
# hackerrank: your_username
# instagram: your_username
# keybase: your_username
# linkedin: your_username
# mastodon: your_username
# medium: your_username
# stackoverflow: your_user_id
# telegram: your_username
# twitter: your_username
# unsplash: your_username
# vk: your_username
# website: http://your_website_url
# youtube: your_username

topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/python/python.png

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/javascript/javascript.png

  - name: Bash
    web_url: https://github.com/topics/bash
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/bash/bash.png

  - name: Web design

  - name: Jekyll
    web_url: https://github.com/topics/jekyll
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/jekyll/jekyll.png
