### Site metadata

repository: MichaelCurrin/MichaelCurrin.github.io

### Build settings ###

url: https://michaelcurrin.github.io
baseurl: ""

permalink: pretty

google_analytics: UA-87705880-9

# Normally you don't need the plugins field if you have :jekyll_plugins but this was needed to avod
# a build error.
plugins:
  - jekyll-octicons

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - LICENSE
  - LICENSE-source
  - README.md
  - Makefile
  # Exclude in Jekyll 3 only
  - vendor/
  - Gemfile

### Theme settings ###

layout: stacked # stacked | sidebar

style: dark # light | dark

dark:
  icon_color: "#ffffff"
light:
  icon_color: "#24292e"

projects:
  sort_by: stars # pushed | stars
  limit: 12
  exclude:
    archived: true
    forks: false
    projects:
    # - repo-name

social_media:
  # instagram: your_username
  # linkedin: your_username
  # medium: your_username
  stackoverflow: 6250733
  # twitter: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/python/python.png

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/javascript/javascript.png

  - name: Bash
    web_url: https://github.com/topics/bash
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/bash/bash.png

  - name: Web design

  - name: Jekyll
    web_url: https://github.com/topics/jekyll
    image_url: https://raw.githubusercontent.com/github/explore/master/topics/jekyll/jekyll.png
